Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/djmarketplace/urls.py changed, reloading.
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
Using selector: EpollSelector
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/djmarketplace/urls.py changed, reloading.
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
Using selector: EpollSelector
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/djmarketplace/settings.py changed, reloading.
Using selector: EpollSelector
Watching for file changes with StatReloader
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
Not Found: /favicon.ico
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
Internal Server Error: /goods_list
Traceback (most recent call last):
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: app_markets_itemgoodsmarketmodel.price

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 73, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
    return real_execute(self, sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: app_markets_itemgoodsmarketmodel.price
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
Internal Server Error: /admin/app_markets/cartmodel/
Traceback (most recent call last):
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: app_markets_cartmodel.total_cost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1815, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
    return real_execute(self, sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: app_markets_cartmodel.total_cost
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
Internal Server Error: /admin/app_markets/itemcartmodel/
Traceback (most recent call last):
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: app_markets_itemcartmodel.item_goods_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1815, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
    return real_execute(self, sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/Django_skillbox/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: app_markets_itemcartmodel.item_goods_id
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
Not Found: /favicon.ico
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
Internal Server Error: /admin/app_markets/goodsmodel/add/
Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: app_markets_goodsmodel.code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1655, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1538, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1584, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1097, in save_model
    obj.save()
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
    return real_execute(self, sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: app_markets_goodsmodel.code
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
Internal Server Error: /admin/app_markets/goodsmodel/add/
Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: app_markets_goodsmodel.code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1655, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1538, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1584, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1097, in save_model
    obj.save()
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
    return real_execute(self, sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: app_markets_goodsmodel.code
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
Internal Server Error: /admin/app_users/profile/
Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: app_users_profile.total_expenses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1813, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
    return real_execute(self, sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: app_users_profile.total_expenses
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
Internal Server Error: /users/account/1
Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: app_users_profile.total_expenses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/detail.py", line 106, in get
    self.object = self.get_object()
  File "/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/views.py", line 44, in get_object
    return User.objects.select_related('profile').get(pk=pk)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
    return real_execute(self, sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: app_users_profile.total_expenses
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
Internal Server Error: /users/registration
Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/views.py", line 22, in form_valid
    status = BuyerStatus.objects.get(status='starter')
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
app_users.models.BuyerStatus.DoesNotExist: BuyerStatus matching query does not exist.
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/models.py changed, reloading.
Using selector: EpollSelector
Watching for file changes with StatReloader
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
Using selector: EpollSelector
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
Internal Server Error: /users/registration
Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/views.py", line 22, in form_valid
    status = BuyerStatus.objects.get(status='starter')
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
app_users.models.BuyerStatus.DoesNotExist: BuyerStatus matching query does not exist.
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/models.py changed, reloading.
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
Internal Server Error: /users/registration
Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/views.py", line 23, in form_valid
    Profile.objects.create(user=user, status=status())
TypeError: 'BuyerStatus' object is not callable
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/models.py changed, reloading.
Using selector: EpollSelector
Watching for file changes with StatReloader
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
Internal Server Error: /users/registration
Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/views.py", line 24, in form_valid
    Profile.objects.create(user=user, status=status())
TypeError: 'BuyerStatus' object is not callable
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/views.py changed, reloading.
Using selector: EpollSelector
Watching for file changes with StatReloader
/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/models.py changed, reloading.
Using selector: EpollSelector
Watching for file changes with StatReloader
Using selector: EpollSelector
Using selector: EpollSelector
Using selector: EpollSelector
Watching for file changes with StatReloader
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
Forbidden (CSRF token missing or incorrect.): /users/registration
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
Internal Server Error: /users/registration
Traceback (most recent call last):
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/home/alex/Django/django_venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/views.py", line 24, in form_valid
    Profile.objects.create(user=user, status=status())
TypeError: 'BuyerStatus' object is not callable
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/store/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
/home/alex/Django/Django_skillbox/python_django/15_DatabasesAdvanced/djmarketplace/app_users/views.py changed, reloading.
Using selector: EpollSelector
Watching for file changes with StatReloader
User logged in
Starting new HTTPS connection (1): o1211792.ingest.sentry.io:443
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 41
https://o1211792.ingest.sentry.io:443 "POST /api/6349486/envelope/ HTTP/1.1" 200 2
Using selector: EpollSelector
Using selector: EpollSelector
